"""add professional_ai_proposals

Revision ID: f336357b7658
Revises: a7a502dd43a9
Create Date: 2026-09-21 15:16:50.490512

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f336357b7658'
down_revision: Union[str, Sequence[str], None] = 'a7a502dd43a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_ai_proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('professional_id', sa.Uuid(), nullable=False),
    sa.Column('feature_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('field_path', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('current_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proposed_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accepted_value', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professional_ai_proposals_expires_at'), 'professional_ai_proposals', ['expires_at'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_feature_key'), 'professional_ai_proposals', ['feature_key'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_field_path'), 'professional_ai_proposals', ['field_path'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_id'), 'professional_ai_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_impact'), 'professional_ai_proposals', ['impact'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_professional_id'), 'professional_ai_proposals', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_ai_proposals_status'), 'professional_ai_proposals', ['status'], unique=False)
    op.alter_column('knowledge_documents', 'title',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=200),
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'category',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=100),
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_knowledge_documents_embedding_hnsw'), table_name='knowledge_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('portfolio_works', 'gallery',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_work_service_id'), table_name='portfolio_works')
    op.create_index(op.f('ix_portfolio_works_service_id'), 'portfolio_works', ['service_id'], unique=False)
    op.drop_constraint(op.f('portfolio_works_service_id_fkey'), 'portfolio_works', type_='foreignkey')
    op.create_foreign_key(None, 'portfolio_works', 'professional_services', ['service_id'], ['id'])
    op.alter_column('professional_portfolios', 'payment_methods',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('professional_portfolios', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('professional_portfolios', 'languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_portfolio_average_rating'), table_name='professional_portfolios')
    op.drop_index(op.f('ix_portfolio_city'), table_name='professional_portfolios')
    op.drop_index(op.f('ix_portfolio_is_featured'), table_name='professional_portfolios')
    op.alter_column('professional_services', 'gallery',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('professional_services', 'whats_included',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('professional_services', 'whats_excluded',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('professional_services', 'faqs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_follows_followed'), table_name='user_follows')
    op.drop_index(op.f('idx_user_follows_follower'), table_name='user_follows')
    op.drop_constraint(op.f('user_follows_follower_id_fkey'), 'user_follows', type_='foreignkey')
    op.drop_constraint(op.f('user_follows_followed_id_fkey'), 'user_follows', type_='foreignkey')
    op.create_foreign_key(None, 'user_follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'user_follows', 'users', ['followed_id'], ['id'])
    op.create_index(op.f('ix_users_account_type'), 'users', ['account_type'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'verification_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_account_type'), table_name='users')
    op.drop_constraint(None, 'user_follows', type_='foreignkey')
    op.drop_constraint(None, 'user_follows', type_='foreignkey')
    op.create_foreign_key(op.f('user_follows_followed_id_fkey'), 'user_follows', 'users', ['followed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('user_follows_follower_id_fkey'), 'user_follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_user_follows_follower'), 'user_follows', ['follower_id'], unique=False)
    op.create_index(op.f('idx_user_follows_followed'), 'user_follows', ['followed_id'], unique=False)
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.alter_column('professional_services', 'faqs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('professional_services', 'whats_excluded',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('professional_services', 'whats_included',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('professional_services', 'gallery',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_portfolio_is_featured'), 'professional_portfolios', ['is_featured', 'featured_until'], unique=False)
    op.create_index(op.f('ix_portfolio_city'), 'professional_portfolios', ['city'], unique=False)
    op.create_index(op.f('ix_portfolio_average_rating'), 'professional_portfolios', ['average_rating'], unique=False)
    op.alter_column('professional_portfolios', 'languages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('professional_portfolios', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('professional_portfolios', 'payment_methods',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'portfolio_works', type_='foreignkey')
    op.create_foreign_key(op.f('portfolio_works_service_id_fkey'), 'portfolio_works', 'professional_services', ['service_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_portfolio_works_service_id'), table_name='portfolio_works')
    op.create_index(op.f('ix_work_service_id'), 'portfolio_works', ['service_id'], unique=False)
    op.alter_column('portfolio_works', 'gallery',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('idx_knowledge_documents_embedding_hnsw'), 'knowledge_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('knowledge_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('knowledge_documents', 'category',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('knowledge_documents', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('knowledge_documents', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_professional_ai_proposals_status'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_professional_id'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_impact'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_id'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_field_path'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_feature_key'), table_name='professional_ai_proposals')
    op.drop_index(op.f('ix_professional_ai_proposals_expires_at'), table_name='professional_ai_proposals')
    op.drop_table('professional_ai_proposals')
    # ### end Alembic commands ###
